### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by Ghabry** [CherryDT/DynRPG#1]
Hey! Cool that you decided to open source DynRPG.

I know that the RPG Maker community does not care alot about copyright and licensing but it would be good if you could add some kind of open source license to this project.

Otherwise this cannot be modified/forked in a legal way.

**Comment by CherryDT** [comment]
There is a license included: https://github.com/CherryDT/DynRPG/blob/master/LICENSE

Am I missing something?
